M48
; DRILL file {KiCad (6.0.8)} date Sat 22 Oct 2022 10:51:43 AM CDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-22T10:51:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X112.395Y-70.485
X112.395Y-99.695
X152.4Y-70.485
X152.4Y-99.695
T0
M30
